export interface DemoBranchConfig {
  enabled: boolean;
  submissionNumber: number | null;
  companyName: string | null;
  contactName: string | null;
  branchName: string | null;
  generatedAt: string | null;
  branding: DemoBranchBrandingConfig | null;
  navigationPriorityHrefs: string[];
  pdf: DemoBranchPdfConfig | null;
  welcome: DemoBranchWelcomeConfig | null;
}

export interface DemoBranchBrandingConfig {
  appName: string;
  shortAppName: string;
  companyName: string;
  brandColor: string;
  brandColorHover: string;
  brandColorLight: string;
  backgroundColor: string;
  logoPath: string;
  faviconPath: string;
  sourceUrl: string | null;
}

export interface DemoBranchPdfConfig {
  registeredOffice: string;
  contactLine: string;
  registrationLine: string;
}

export interface DemoBranchWelcomeConfig {
  companyDisplayName: string;
  industryLabel: string | null;
  operatingRegion: string | null;
  companySizeLabel: string | null;
  primaryDemoObjectiveLabel: string | null;
  priorityModuleLabels: string[];
  painPointLabels: string[];
  teamLabels: string[];
  assetLabels: string[];
  documentOutputLabels: string[];
}

export const demoBranchConfig: DemoBranchConfig = {
  enabled: true,
  submissionNumber: 5,
  companyName: "Railway Electrical Services",
  contactName: "Alannah Dunnachie",
  branchName: "demo/railway-electrical-services-submission-5",
  generatedAt: "2026-06-22T17:17:17.149Z",
  branding: {
  "appName": "Railway Electrical Services Operations",
  "shortAppName": "Railway Electrical Ser",
  "companyName": "Railway Electrical Services",
  "brandColor": "#ffffff",
  "brandColorHover": "#DBDBDB",
  "brandColorLight": "#FFFFFF",
  "backgroundColor": "#0f172a",
  "logoPath": "/demo-personalisation/submission-5/logo.png",
  "faviconPath": "/demo-personalisation/submission-5/favicon.svg",
  "sourceUrl": "https://www.railwayelectricalservices.co.uk"
},
  navigationPriorityHrefs: [
  "/timesheets",
  "/approvals",
  "/van-inspections",
  "/plant-inspections",
  "/hgv-inspections",
  "/projects",
  "/absence",
  "/absence/manage",
  "/reports"
],
  pdf: {
  "registeredOffice": "Railway Electrical Services, UK wide",
  "contactLine": "Telephone: 07736686796",
  "registrationLine": "Personalised demo output generated by Railway Electrical Services"
},
  welcome: {
  "companyDisplayName": "Railway Electrical Services",
  "industryLabel": "Other",
  "operatingRegion": "UK wide",
  "companySizeLabel": "25 to 75 people",
  "primaryDemoObjectiveLabel": "Managers get better live visibility",
  "priorityModuleLabels": [
    "Timesheets and approvals",
    "Van, HGV, or plant daily checks",
    "Projects, RAMS, and compliance documents",
    "Absence and holiday management",
    "Reports and management visibility"
  ],
  "painPointLabels": [
    "Late or inaccurate timesheets",
    "Too much duplicate spreadsheet work",
    "RAMS, toolbox talks, or documents are hard to control",
    "Reporting takes too long",
    "Vehicle or plant defects are hard to track",
    "Absence planning is unclear"
  ],
  "teamLabels": [
    "Management",
    "Office/admin",
    "Civils/site teams",
    "Plant"
  ],
  "assetLabels": [
    "Vans or light commercial vehicles",
    "Small tools and equipment",
    "Plant and heavy machinery"
  ],
  "documentOutputLabels": [
    "Timesheet PDFs",
    "RAMS or project documents",
    "Email notifications",
    "Inspection or defect PDFs",
    "Quote PDFs",
    "App icon/install screen"
  ]
},
};
