import { demoBranchConfig } from '@/lib/config/demo-branch-config';

export const appModes = {
  development: 'development',
  template: 'template',
  demo: 'demo',
  production: 'production',
} as const;

export type AppMode = (typeof appModes)[keyof typeof appModes];

export interface DemoPersona {
  key: 'admin' | 'manager' | 'employee' | 'contractor';
  label: string;
  name: string;
  description: string;
  email: string;
  password: string;
}

export interface TemplateBrandingConfig {
  appName: string;
  shortAppName: string;
  companyName: string;
  registeredAddress: string;
  supportEmail: string;
  supportPhone: string;
  adminEmail: string;
  publicUrl: string;
  logoPath: string;
  faviconPath: string;
  brandColor: string;
  brandColorHover: string;
  brandColorLight: string;
  backgroundColor: string;
  registrationText: string;
}

export interface TemplatePublicConfig {
  mode: AppMode;
  isDemoMode: boolean;
  demoEmailDomain: string;
  branding: TemplateBrandingConfig;
  demoPersonas: DemoPersona[];
}

function readPublicEnv(key: string, fallback: string): string {
  const value = process.env[key];
  return value && value.trim().length > 0 ? value.trim() : fallback;
}

function readDemoBrandingValue(
  key: string,
  demoValue: string | null | undefined,
  fallback: string
): string {
  if (demoBranchConfig.enabled && demoValue && demoValue.trim().length > 0) {
    return demoValue.trim();
  }

  return readPublicEnv(key, fallback);
}

function normaliseMode(value: string | undefined): AppMode {
  if (value === appModes.template || value === appModes.demo || value === appModes.production) {
    return value;
  }

  return appModes.development;
}

function trimLeadingAt(value: string): string {
  return value.startsWith('@') ? value.slice(1) : value;
}

const mode = normaliseMode(process.env.NEXT_PUBLIC_APP_MODE || process.env.APP_MODE);
const demoEmailDomain = trimLeadingAt(readPublicEnv('NEXT_PUBLIC_DEMO_EMAIL_DOMAIN', 'demo.example.test'));

export const templateConfig: TemplatePublicConfig = {
  mode,
  isDemoMode: mode === appModes.demo,
  demoEmailDomain,
  branding: {
    appName: readDemoBrandingValue('NEXT_PUBLIC_APP_NAME', demoBranchConfig.branding?.appName, 'DigiDocs'),
    shortAppName: readDemoBrandingValue('NEXT_PUBLIC_SHORT_APP_NAME', demoBranchConfig.branding?.shortAppName, 'DigiDocs'),
    companyName: readDemoBrandingValue('NEXT_PUBLIC_COMPANY_NAME', demoBranchConfig.branding?.companyName, 'DigiDocs Demo Ltd'),
    registeredAddress: readDemoBrandingValue(
      'NEXT_PUBLIC_COMPANY_ADDRESS',
      demoBranchConfig.pdf?.registeredOffice,
      'Example House, Template Street, Example Town'
    ),
    supportEmail: readPublicEnv('NEXT_PUBLIC_SUPPORT_EMAIL', 'support@example.test'),
    supportPhone: readDemoBrandingValue('NEXT_PUBLIC_SUPPORT_PHONE', demoBranchConfig.pdf?.contactLine, ''),
    adminEmail: readPublicEnv('NEXT_PUBLIC_ADMIN_EMAIL', 'template-admin@example.com'),
    publicUrl: readPublicEnv(
      'NEXT_PUBLIC_APP_URL',
      readPublicEnv('NEXT_PUBLIC_SITE_URL', 'http://localhost:4000')
    ),
    logoPath: readDemoBrandingValue('NEXT_PUBLIC_LOGO_PATH', demoBranchConfig.branding?.logoPath, '/images/logo.svg'),
    faviconPath: readDemoBrandingValue('NEXT_PUBLIC_FAVICON_PATH', demoBranchConfig.branding?.faviconPath, '/favicon.svg'),
    brandColor: readDemoBrandingValue('NEXT_PUBLIC_BRAND_COLOR', demoBranchConfig.branding?.brandColor, '#F1D64A'),
    brandColorHover: readDemoBrandingValue(
      'NEXT_PUBLIC_BRAND_COLOR_HOVER',
      demoBranchConfig.branding?.brandColorHover,
      '#D4B83A'
    ),
    brandColorLight: readDemoBrandingValue(
      'NEXT_PUBLIC_BRAND_COLOR_LIGHT',
      demoBranchConfig.branding?.brandColorLight,
      '#FEF3C7'
    ),
    backgroundColor: readDemoBrandingValue(
      'NEXT_PUBLIC_PWA_BACKGROUND_COLOR',
      demoBranchConfig.branding?.backgroundColor,
      '#0f172a'
    ),
    registrationText: readDemoBrandingValue(
      'NEXT_PUBLIC_COMPANY_REGISTRATION',
      demoBranchConfig.pdf?.registrationLine,
      'Generated by DigiDocs'
    ),
  },
  demoPersonas: [
    {
      key: 'admin',
      label: 'Administrator',
      name: 'Alannah Dunnachie',
      description: 'Railway Electrical Services admin view',
      email: 'a-dunnachie@rail-elec.co.uk',
      password: 'DemoPass123!',
    },
    {
      key: 'manager',
      label: 'Manager',
      name: 'Morgan Reid',
      description: 'Team oversight, approvals, and reports',
      email: `morgan.reid@${demoEmailDomain}`,
      password: 'DemoPass123!',
    },
    {
      key: 'employee',
      label: 'Employee',
      name: 'Jamie Carter',
      description: 'Timesheets, inspections, and messages',
      email: `jamie.carter@${demoEmailDomain}`,
      password: 'DemoPass123!',
    },
    {
      key: 'contractor',
      label: 'Contractor',
      name: 'Taylor Brooks',
      description: 'Limited access demo contractor profile',
      email: `taylor.brooks@${demoEmailDomain}`,
      password: 'DemoPass123!',
    },
  ],
};

export function getTemplateConfig(): TemplatePublicConfig {
  return templateConfig;
}

export function isDemoModeEnabled(): boolean {
  return templateConfig.isDemoMode;
}

export function getDemoPersonas(): DemoPersona[] {
  return templateConfig.demoPersonas;
}

interface RgbColour {
  r: number;
  g: number;
  b: number;
}

function hexToRgb(hexValue: string): RgbColour | null {
  const normalized = hexValue.trim().replace(/^#/u, '');
  if (!/^[\da-f]{6}$/iu.test(normalized)) {
    return null;
  }

  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16),
  };
}

function hexToHslTriplet(hexValue: string, fallback: string): string {
  const rgb = hexToRgb(hexValue);
  if (!rgb) {
    return fallback;
  }

  const r = rgb.r / 255;
  const g = rgb.g / 255;
  const b = rgb.b / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const lightness = (max + min) / 2;
  const delta = max - min;

  if (delta === 0) {
    return `0 0% ${Math.round(lightness * 100)}%`;
  }

  const saturation = delta / (1 - Math.abs(2 * lightness - 1));
  const hue =
    max === r
      ? 60 * (((g - b) / delta) % 6)
      : max === g
        ? 60 * ((b - r) / delta + 2)
        : 60 * ((r - g) / delta + 4);

  return `${Math.round((hue + 360) % 360)} ${Math.round(saturation * 100)}% ${Math.round(lightness * 100)}%`;
}

export function getTemplateBrandCssVariables(): Record<string, string> {
  const backgroundColor = hexToHslTriplet(templateConfig.branding.backgroundColor, '222 47% 11%');

  return {
    '--background': backgroundColor,
    '--card': backgroundColor,
    '--popover': backgroundColor,
    '--brand-yellow': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
    '--brand-yellow-hover': hexToHslTriplet(templateConfig.branding.brandColorHover, '48 73% 56%'),
    '--brand-yellow-light': hexToHslTriplet(templateConfig.branding.brandColorLight, '48 100% 94%'),
    '--primary': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
    '--ring': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
  };
}
